//
// Created by Leonard on 2025-02-03.
//

#ifndef CONFIG_H
#define CONFIG_H

// OUTPUT QUALITY
#define OUTPUT_WIDTH 1920
#define OUTPUT_HEIGHT 1080
#define SAMPLE_GRID_SIZE 1

// PATH TRACING COMPLEXITY
#define DEPTH_LIMIT 10
#define MIN_LIGHT_FACTOR 0.01
#define MAX_INTERNAL_BOUNCES 8

// FEATURES
#define ENABLE_POLARIZATION 0
#define ENABLE_DISPERSION 0

// DEBUG
#define DEBUG_ASSERTS 1
#define DEBUG_SHADE_NORMALS 0

#endif //CONFIG_H
